version: "3.7"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - /docker_projeto1/php/admin:/app

    networks:
      - minha-rede

  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /docker_projeto1/banco_mysql:/var/lib/mysql

    networks:
      - minha-rede

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - minha-rede

networks:
   minha-rede:
     driver: bridge
